/**
 * 错误码定义
 */
export enum ErrorCode {
  // 认证错误 (1000-1099)
  INVALID_CREDENTIALS = 1000,
  TOKEN_EXPIRED = 1001,
  TOKEN_INVALID = 1002,
  ACCOUNT_LOCKED = 1003,
  INSUFFICIENT_PERMISSIONS = 1004,

  // 会话错误 (1100-1199)
  DEVICE_NOT_FOUND = 1100,
  DEVICE_OFFLINE = 1101,
  DEVICE_BUSY = 1102,
  SESSION_NOT_FOUND = 1103,
  SESSION_TIMEOUT = 1104,
  SESSION_CONFLICT = 1105,

  // WebRTC 错误 (1200-1299)
  WEBRTC_NEGOTIATION_FAILED = 1200,
  WEBRTC_CONNECTION_FAILED = 1201,
  ICE_GATHERING_FAILED = 1202,

  // 协议错误 (1300-1399)
  INVALID_MESSAGE_FORMAT = 1300,
  UNSUPPORTED_MESSAGE_TYPE = 1301,
  MESSAGE_VALIDATION_FAILED = 1302,

  // 服务器错误 (1400-1499)
  INTERNAL_SERVER_ERROR = 1400,
  SERVICE_UNAVAILABLE = 1401,
  RATE_LIMIT_EXCEEDED = 1402,

  // 客户端错误 (1500-1599)
  CAPTURE_FAILED = 1500,
  ENCODING_FAILED = 1501,
  INPUT_INJECTION_FAILED = 1502,
  CLIPBOARD_SYNC_FAILED = 1503,
  FILE_TRANSFER_FAILED = 1504,
}

/**
 * 错误码到符号名称的映射
 */
export const ERROR_NAMES: Record<ErrorCode, string> = {
  [ErrorCode.INVALID_CREDENTIALS]: "INVALID_CREDENTIALS",
  [ErrorCode.TOKEN_EXPIRED]: "TOKEN_EXPIRED",
  [ErrorCode.TOKEN_INVALID]: "TOKEN_INVALID",
  [ErrorCode.ACCOUNT_LOCKED]: "ACCOUNT_LOCKED",
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: "INSUFFICIENT_PERMISSIONS",
  [ErrorCode.DEVICE_NOT_FOUND]: "DEVICE_NOT_FOUND",
  [ErrorCode.DEVICE_OFFLINE]: "DEVICE_OFFLINE",
  [ErrorCode.DEVICE_BUSY]: "DEVICE_BUSY",
  [ErrorCode.SESSION_NOT_FOUND]: "SESSION_NOT_FOUND",
  [ErrorCode.SESSION_TIMEOUT]: "SESSION_TIMEOUT",
  [ErrorCode.SESSION_CONFLICT]: "SESSION_CONFLICT",
  [ErrorCode.WEBRTC_NEGOTIATION_FAILED]: "WEBRTC_NEGOTIATION_FAILED",
  [ErrorCode.WEBRTC_CONNECTION_FAILED]: "WEBRTC_CONNECTION_FAILED",
  [ErrorCode.ICE_GATHERING_FAILED]: "ICE_GATHERING_FAILED",
  [ErrorCode.INVALID_MESSAGE_FORMAT]: "INVALID_MESSAGE_FORMAT",
  [ErrorCode.UNSUPPORTED_MESSAGE_TYPE]: "UNSUPPORTED_MESSAGE_TYPE",
  [ErrorCode.MESSAGE_VALIDATION_FAILED]: "MESSAGE_VALIDATION_FAILED",
  [ErrorCode.INTERNAL_SERVER_ERROR]: "INTERNAL_SERVER_ERROR",
  [ErrorCode.SERVICE_UNAVAILABLE]: "SERVICE_UNAVAILABLE",
  [ErrorCode.RATE_LIMIT_EXCEEDED]: "RATE_LIMIT_EXCEEDED",
  [ErrorCode.CAPTURE_FAILED]: "CAPTURE_FAILED",
  [ErrorCode.ENCODING_FAILED]: "ENCODING_FAILED",
  [ErrorCode.INPUT_INJECTION_FAILED]: "INPUT_INJECTION_FAILED",
  [ErrorCode.CLIPBOARD_SYNC_FAILED]: "CLIPBOARD_SYNC_FAILED",
  [ErrorCode.FILE_TRANSFER_FAILED]: "FILE_TRANSFER_FAILED",
};

/**
 * 获取错误码的符号名称
 */
export function getErrorName(code: number): string {
  return ERROR_NAMES[code as ErrorCode] || "UNKNOWN_ERROR";
}
